version: 1
accounts:
- name: alice
  mnemonic: "entry garbage bike poem grunt negative easily annual miss happy license blur false fringe program picture inner tape dismiss eagle include quality drill master"
  coins:
  - 200000000000000000000swtr
- name: bob
  coins:
  - 200000000000000000000swtr
- name: jane
  coins:
    - 200000000000000000000swtr
  mnemonic: "cargo ramp supreme review change various throw air figure humble soft steel slam pole betray inhale already dentist enough away office apple sample glue"
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 500000swtr
validators:
- name: alice
  bonded: 100000000swtr
genesis:
  chain_id: "swisstronik_4141-1"
  app_state:
    staking:
      params:
        bond_denom: "swtr"
  consensus_params:
    block:
      max_gas: "20000000"