version: '3'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9999:9090"
    restart: unless-stopped
    volumes:
      - prometheus-data:/prometheus
      - ./monitoring:/config
    command:
      - "--config.file=/config/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  aesm:
    build:
      dockerfile: ./docker/aesm.Dockerfile
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    volumes:
      - /tmp/aesmd:/var/run/aesmd
    restart: always
    
  node:
    build:
      dockerfile: ./docker/node.Dockerfile
      target: node
      context: .
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    depends_on:
      - aesm
    volumes:
      - /tmp/aesmd:/var/run/aesmd
      - /home/mikkysnow/.swisstronik:/root/.swisstronik
    ports:
      - "26656:26656"
      - "26657:26657"
      - "1317:1317"
    command: swisstronikd start
    restart: always
