global:
    scrape_interval: 10s
    scrape_timeout: 5s

scrape_configs:
  - job_name: 'swisstronik'
    static_configs:
      - targets: ['172.17.0.1:26660']
        labels:
          instance: validator